
package com.jsanz.metanalizer.ws.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.jsanz.metanalizer.ws.ConsultaSimple;
import com.jsanz.metanalizer.ws.IConsultaSimple;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultaSimpleService", targetNamespace = "http://ws.metanalizer.jsanz.com/", wsdlLocation = "http://localhost:8081/consulta-simple?wsdl")
public class ConsultaSimpleService
    extends Service
{

    private final static URL CONSULTASIMPLESERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSULTASIMPLESERVICE_EXCEPTION;
    private final static QName CONSULTASIMPLESERVICE_QNAME = new QName("http://ws.metanalizer.jsanz.com/", "ConsultaSimpleService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/consulta-simple?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTASIMPLESERVICE_WSDL_LOCATION = url;
        CONSULTASIMPLESERVICE_EXCEPTION = e;
    }

    public ConsultaSimpleService() {
        super(__getWsdlLocation(), CONSULTASIMPLESERVICE_QNAME);
    }

    public ConsultaSimpleService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTASIMPLESERVICE_QNAME, features);
    }

    public ConsultaSimpleService(URL wsdlLocation) {
        super(wsdlLocation, CONSULTASIMPLESERVICE_QNAME);
    }

    public ConsultaSimpleService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTASIMPLESERVICE_QNAME, features);
    }

    public ConsultaSimpleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaSimpleService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultaSimple
     */
    @WebEndpoint(name = "ConsultaSimplePort")
    public IConsultaSimple getConsultaSimplePort() {
        return super.getPort(new QName("http://ws.metanalizer.jsanz.com/", "ConsultaSimplePort"), IConsultaSimple.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaSimple
     */
    @WebEndpoint(name = "ConsultaSimplePort")
    public ConsultaSimple getConsultaSimplePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.metanalizer.jsanz.com/", "ConsultaSimplePort"), ConsultaSimple.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTASIMPLESERVICE_EXCEPTION!= null) {
            throw CONSULTASIMPLESERVICE_EXCEPTION;
        }
        return CONSULTASIMPLESERVICE_WSDL_LOCATION;
    }

}
